import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import {
  getResolvedTools,
  refreshResolvedTools,
} from "./deps/resolveTools.js";
import { assertHgRepo } from "./prerequisites.js";

export interface AuthorMappingEntry {
  hgAuthor: string;
  gitName?: string;
  gitEmail?: string;
  /** Full Git author string; overrides gitName/gitEmail when set. */
  gitIdentity?: string;
}

export interface HgAuthorScanRow {
  hgAuthor: string;
  commitCount: number;
  suggestedName?: string;
  suggestedEmail?: string;
}

/** Read author lines from full hg history (Mercurial has no `all` revset). */
function hgLogAuthors(hgRepo: string): string {
  refreshResolvedTools();
  const hg = getResolvedTools().hg;
  if (!hg) {
    throw new Error("Mercurial (hg) is not installed or not on PATH");
  }

  const attempts: { args: string[]; label: string }[] = [
    {
      label: "0:tip",
      args: ["-R", hgRepo, "log", "-r", "0:tip", "-T", "{author}\n"],
    },
    {
      label: "default walk",
      args: ["-R", hgRepo, "log", "-T", "{author}\n"],
    },
  ];

  let lastErr = "";
  for (const { args, label } of attempts) {
    const r = spawnSync(hg, args, {
      encoding: "utf8",
      windowsHide: true,
      env: process.env,
    });
    if (r.status === 0) return (r.stdout ?? "").trimEnd();
    lastErr =
      (r.stderr ?? r.stdout ?? "").trim() ||
      `hg log failed (${label}, exit ${r.status ?? "?"})`;
  }

  throw new Error(lastErr || "hg log failed");
}

/** Heuristic parse of Mercurial author strings (e.g. `Name <email>`). */
export function parseHgAuthorString(hgAuthor: string): {
  name?: string;
  email?: string;
} {
  const trimmed = hgAuthor.trim();
  const angle = trimmed.match(/^(.+?)\s*<([^>]+)>\s*$/);
  if (angle) {
    return { name: angle[1]!.trim(), email: angle[2]!.trim() };
  }
  const emailOnly = trimmed.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/);
  if (emailOnly) return { email: trimmed };
  if (trimmed.includes("@")) {
    const parts = trimmed.split(/\s+/);
    const emailPart = parts.find((p) => p.includes("@"));
    if (emailPart) {
      const name = parts.filter((p) => p !== emailPart).join(" ").trim();
      return {
        name: name || undefined,
        email: emailPart.replace(/^<|>$/g, ""),
      };
    }
  }
  return { name: trimmed || undefined };
}

export function gitIdentityFromEntry(entry: AuthorMappingEntry): string | undefined {
  const explicit = entry.gitIdentity?.trim();
  if (explicit) return explicit;
  const name = entry.gitName?.trim();
  const email = entry.gitEmail?.trim();
  if (name && email) return `${name} <${email}>`;
  if (email) return email;
  if (name) return name;
  return undefined;
}

export function isAuthorMappingComplete(entry: AuthorMappingEntry): boolean {
  return Boolean(gitIdentityFromEntry(entry));
}

function escapeMapString(value: string): string {
  return JSON.stringify(value);
}

export function serializeAuthorsMap(entries: AuthorMappingEntry[]): string {
  const lines = [
    "# Generated by hg-to-git (hg-fast-export author map, UTF-8)",
    '# Format: "hg author string"="git author string"',
    "",
  ];
  const seen = new Set<string>();
  for (const entry of entries) {
    const hg = entry.hgAuthor.trim();
    if (!hg || seen.has(hg)) continue;
    const git = gitIdentityFromEntry(entry);
    if (!git) continue;
    seen.add(hg);
    lines.push(`${escapeMapString(hg)}=${escapeMapString(git)}`);
  }
  return lines.join("\n") + (lines.length > 3 ? "\n" : "");
}

function decodeMapInner(inner: string): string {
  try {
    return JSON.parse(
      `"${inner.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`,
    ) as string;
  } catch {
    return inner;
  }
}

export function parseAuthorsMapContent(content: string): AuthorMappingEntry[] {
  const entries: AuthorMappingEntry[] = [];
  const lineRe = /^"((?:\\.|[^"\\])*)"\s*=\s*"((?:\\.|[^"\\])*)"\s*$/;

  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const m = line.match(lineRe);
    if (!m) continue;
    const hgAuthor = decodeMapInner(m[1]!);
    const gitIdentity = decodeMapInner(m[2]!);
    const parsed = parseHgAuthorString(gitIdentity);
    entries.push({
      hgAuthor,
      gitIdentity,
      gitName: parsed.name,
      gitEmail: parsed.email,
    });
  }
  return entries;
}

export async function readAuthorsMapFile(filePath: string): Promise<AuthorMappingEntry[]> {
  if (!existsSync(filePath)) return [];
  const content = await readFile(filePath, "utf8");
  return parseAuthorsMapContent(content);
}

export function scanHgAuthors(hgRepo: string): HgAuthorScanRow[] {
  assertHgRepo(hgRepo);
  const out = hgLogAuthors(hgRepo);
  const counts = new Map<string, number>();
  for (const line of out.split(/\r?\n/)) {
    const author = line.trim();
    if (!author) continue;
    counts.set(author, (counts.get(author) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([hgAuthor, commitCount]) => {
      const { name, email } = parseHgAuthorString(hgAuthor);
      return {
        hgAuthor,
        commitCount,
        suggestedName: name,
        suggestedEmail: email,
      };
    })
    .sort((a, b) => b.commitCount - a.commitCount || a.hgAuthor.localeCompare(b.hgAuthor));
}

export function mergeAuthorMappings(
  existing: AuthorMappingEntry[],
  scanned: HgAuthorScanRow[],
): AuthorMappingEntry[] {
  const byHg = new Map(existing.map((e) => [e.hgAuthor, { ...e }]));
  for (const row of scanned) {
    if (byHg.has(row.hgAuthor)) continue;
    byHg.set(row.hgAuthor, {
      hgAuthor: row.hgAuthor,
      gitName: row.suggestedName,
      gitEmail: row.suggestedEmail,
    });
  }
  return [...byHg.values()].sort(
    (a, b) => a.hgAuthor.localeCompare(b.hgAuthor),
  );
}

export function defaultAuthorsMapPath(gitRepo: string): string {
  return path.join(gitRepo, ".hg-to-git", "authors.map");
}

export async function writeProjectAuthorsMap(
  gitRepo: string,
  entries: AuthorMappingEntry[],
): Promise<string> {
  const mapPath = defaultAuthorsMapPath(gitRepo);
  await mkdir(path.dirname(mapPath), { recursive: true });
  await writeFile(mapPath, serializeAuthorsMap(entries), "utf8");
  return mapPath;
}

/** Resolve authors.map path for conversion (project mappings take precedence). */
export async function prepareAuthorsMapForConvert(opts: {
  gitRepo: string;
  authorMappings?: AuthorMappingEntry[];
  authorsMap?: string;
}): Promise<string | undefined> {
  const mappings = opts.authorMappings?.filter((e) => e.hgAuthor.trim());
  if (mappings?.length) {
    const complete = mappings.filter(isAuthorMappingComplete);
    if (complete.length === 0) return undefined;
    return writeProjectAuthorsMap(opts.gitRepo, mappings);
  }
  if (opts.authorsMap?.trim() && existsSync(opts.authorsMap)) {
    return path.resolve(opts.authorsMap);
  }
  const generated = defaultAuthorsMapPath(opts.gitRepo);
  if (existsSync(generated)) return generated;
  return undefined;
}

export async function apiScanHgAuthors(hgRepo: string): Promise<HgAuthorScanRow[]> {
  if (!hgRepo?.trim()) throw new Error("hgRepo is required");
  return scanHgAuthors(hgRepo);
}

export async function apiParseAuthorsMapFile(
  filePath: string,
): Promise<AuthorMappingEntry[]> {
  if (!filePath?.trim()) throw new Error("filePath is required");
  if (!existsSync(filePath)) throw new Error(`File not found: ${filePath}`);
  return readAuthorsMapFile(filePath);
}
