import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { loadConfig, resolveConfigPath } from "./config.js";
import { getResolvedTools } from "./deps/resolveTools.js";

export interface AuthorMapEntry {
  hgAuthor: string;
  gitName?: string;
  gitEmail?: string;
  gitIdentity?: string;
}

/** hg-fast-export / git fast-import rejects empty display names. */
const FALLBACK_AUTHOR_MAPPINGS: Record<string, string> = {
  "": "Mercurial <devnull@localhost>",
  "<>": "Mercurial <devnull@localhost>",
  "devnull@localhost": "Mercurial <devnull@localhost>",
  "<devnull@localhost>": "Mercurial <devnull@localhost>",
  "<> <devnull@localhost>": "Mercurial <devnull@localhost>",
};

export function defaultAuthorsMapPath(gitRepo: string): string {
  return path.join(gitRepo, ".hg-to-git", "authors.map");
}

export function parseHgAuthorString(raw: string): {
  name?: string;
  email?: string;
} {
  const s = raw.trim();
  const angled = s.match(/^([^<]*?)\s*<([^>]+)>$/);
  if (angled) {
    const name = angled[1]?.trim();
    const email = angled[2]?.trim();
    return {
      name: name || undefined,
      email: email || undefined,
    };
  }
  if (/^[^\s<]+@[^\s>]+$/.test(s)) return { email: s };
  if (s) return { name: s };
  return {};
}

export function needsAuthorMapping(hgAuthor: string): boolean {
  const key = hgAuthor.trim();
  if (key in FALLBACK_AUTHOR_MAPPINGS) return true;
  const { name, email } = parseHgAuthorString(key);
  if (!name || name === "<>" || /^[<>]+$/.test(name)) return true;
  if (email && !email.includes("@")) return true;
  return false;
}

export function suggestGitIdentity(hgAuthor: string): string {
  const { name, email } = parseHgAuthorString(hgAuthor.trim());
  if (
    name &&
    email &&
    name !== "<>" &&
    !/^[<>]+$/.test(name) &&
    email.includes("@")
  ) {
    return `${name} <${email}>`;
  }
  if (email?.includes("@") && name && name !== "<>" && !/^[<>]+$/.test(name)) {
    return `${name} <${email}>`;
  }
  if (email?.includes("@")) {
    const local = email.split("@")[0] || "Mercurial";
    return `${local} <${email}>`;
  }
  return "Mercurial <devnull@localhost>";
}

export function gitIdentityFromEntry(entry: AuthorMapEntry): string {
  if (entry.gitIdentity?.trim()) return entry.gitIdentity.trim();
  const name = entry.gitName?.trim();
  const email = entry.gitEmail?.trim();
  if (name && email) return `${name} <${email}>`;
  if (name) return name;
  if (email) return email;
  return "";
}

export function isAuthorMappingComplete(entry: AuthorMapEntry): boolean {
  return Boolean(
    entry.gitIdentity?.trim() ||
      entry.gitName?.trim() ||
      entry.gitEmail?.trim(),
  );
}

function unescapePythonString(raw: string): string {
  return raw
    .replace(/\\n/g, "\n")
    .replace(/\\r/g, "\r")
    .replace(/\\t/g, "\t")
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, "\\");
}

function escapePythonString(raw: string): string {
  return raw
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

export function parseAuthorsMapContent(text: string): AuthorMapEntry[] {
  const entries: AuthorMapEntry[] = [];
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const m = trimmed.match(/^"(.*)"="(.*)"$/);
    if (!m) continue;
    const hgAuthor = unescapePythonString(m[1]);
    const gitIdentity = unescapePythonString(m[2]);
    const parsed = parseHgAuthorString(gitIdentity);
    entries.push({
      hgAuthor,
      gitIdentity,
      gitName: parsed.name,
      gitEmail: parsed.email,
    });
  }
  return entries;
}

export function serializeAuthorsMap(entries: AuthorMapEntry[]): string {
  const lines = [
    "# Generated by hg-to-git (hg-fast-export author map, UTF-8)",
    '# Format: "hg author string"="git author string"',
    "",
  ];
  for (const entry of entries) {
    const gitIdentity =
      gitIdentityFromEntry(entry) || suggestGitIdentity(entry.hgAuthor);
    lines.push(
      `"${escapePythonString(entry.hgAuthor)}"="${escapePythonString(gitIdentity)}"`,
    );
  }
  return lines.join("\n") + (entries.length ? "\n" : "");
}

export function mergeAuthorMappings(
  existing: AuthorMapEntry[],
  scanned: Array<{ hgAuthor: string }>,
): AuthorMapEntry[] {
  const byHg = new Map<string, AuthorMapEntry>();
  for (const entry of existing) {
    if (!entry.hgAuthor) continue;
    byHg.set(entry.hgAuthor, entry);
  }
  for (const { hgAuthor } of scanned) {
    if (!hgAuthor || byHg.has(hgAuthor)) continue;
    byHg.set(hgAuthor, {
      hgAuthor,
      gitIdentity: suggestGitIdentity(hgAuthor),
    });
  }
  return [...byHg.values()].sort((a, b) =>
    a.hgAuthor.localeCompare(b.hgAuthor),
  );
}

function listHgAuthorStrings(hgRepo: string): string[] {
  const hg = getResolvedTools().hg;
  if (!hg || !hgRepo.trim() || !existsSync(path.join(hgRepo, ".hg"))) {
    return [];
  }
  const r = spawnSync(
    hg,
    ["-R", hgRepo, "log", "-r", "all()", "-T", "{author|user}\n", "-q"],
    { encoding: "utf8", windowsHide: true, env: process.env, maxBuffer: 64 * 1024 * 1024 },
  );
  if (r.status !== 0) return [];
  const names = new Set<string>();
  for (const line of (r.stdout ?? "").split(/\r?\n/)) {
    const author = line.trim();
    if (author) names.add(author);
  }
  return [...names];
}

function loadAuthorsMapFile(filePath: string): AuthorMapEntry[] {
  if (!existsSync(filePath)) return [];
  return parseAuthorsMapContent(readFileSync(filePath, "utf8"));
}

function entriesFromFallbacks(): AuthorMapEntry[] {
  return Object.entries(FALLBACK_AUTHOR_MAPPINGS).map(([hgAuthor, gitIdentity]) => ({
    hgAuthor,
    gitIdentity,
  }));
}

function entriesNeedingMapping(hgAuthors: string[]): AuthorMapEntry[] {
  return hgAuthors
    .filter((author) => needsAuthorMapping(author))
    .map((hgAuthor) => ({
      hgAuthor,
      gitIdentity: suggestGitIdentity(hgAuthor),
    }));
}

function writeAuthorsMap(gitRepo: string, entries: AuthorMapEntry[]): string {
  const outPath = defaultAuthorsMapPath(gitRepo);
  mkdirSync(path.dirname(outPath), { recursive: true });
  writeFileSync(outPath, serializeAuthorsMap(entries), "utf8");
  return outPath;
}

async function resolveConfiguredAuthorsMapPath(
  gitRepo: string,
  explicit?: string,
): Promise<string | undefined> {
  if (explicit?.trim() && existsSync(explicit)) {
    return path.resolve(explicit);
  }
  const configPath = resolveConfigPath(gitRepo);
  if (!configPath) return undefined;
  try {
    const config = await loadConfig(configPath, { gitRepo, hgRepo: gitRepo });
    if (config.authorsMap && existsSync(config.authorsMap)) {
      return config.authorsMap;
    }
  } catch {
    /* ignore invalid repo config */
  }
  return undefined;
}

/**
 * Build an authors.map for hg-fast-export, fixing malformed hg identities that
 * make git fast-import reject commits (e.g. `<> <devnull@localhost>`).
 */
export async function prepareAuthorsMapForConvert(opts: {
  gitRepo: string;
  hgRepo?: string;
  authorsMap?: string;
}): Promise<string> {
  const sources: AuthorMapEntry[] = [];

  const configured = await resolveConfiguredAuthorsMapPath(
    opts.gitRepo,
    opts.authorsMap,
  );
  if (configured) sources.push(...loadAuthorsMapFile(configured));

  const generated = defaultAuthorsMapPath(opts.gitRepo);
  if (generated !== configured && existsSync(generated)) {
    sources.push(...loadAuthorsMapFile(generated));
  }

  const hgAuthors = opts.hgRepo ? listHgAuthorStrings(opts.hgRepo) : [];
  const merged = mergeAuthorMappings(sources, [
    ...entriesFromFallbacks(),
    ...entriesNeedingMapping(hgAuthors),
  ]);

  return writeAuthorsMap(opts.gitRepo, merged);
}
