import { existsSync, readFileSync } from "node:fs";

/** Mercurial branch name → Git branch name (hg-fast-export -M / -B). */
export type HgToGitBranchMap = Map<string, string>;

const HG_DEFAULT_BRANCH = "default";

/** Parse fast-export style branch map: `"hg"="git"` or `hg=git`. */
export function parseBranchesMapFile(filePath: string): HgToGitBranchMap {
  const map = new Map<string, string>();
  if (!existsSync(filePath)) return map;

  for (const raw of readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#") || line.startsWith("--")) continue;

    const quoted = line.match(/^"([^"]+)"\s*=\s*"([^"]+)"\s*$/);
    if (quoted) {
      map.set(quoted[1], quoted[2]);
      continue;
    }

    const plain = line.match(/^([^=]+?)\s*=\s*(.+?)\s*$/);
    if (plain) {
      map.set(plain[1].trim(), plain[2].trim());
    }
  }

  return map;
}

function quoteMapValue(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function serializeBranchesMap(map: HgToGitBranchMap): string {
  const lines = [
    "# Generated by hg-to-git (hg-fast-export branch map, UTF-8)",
    '# Format: "hg branch"="git branch"',
    "",
  ];
  const entries = [...map.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  for (const [hg, git] of entries) {
    lines.push(`"${quoteMapValue(hg)}"="${quoteMapValue(git)}"`);
  }
  return `${lines.join("\n")}\n`;
}

/** Matches hg-fast-export `sanitize_name` for branches (with auto_sanitize on). */
export function sanitizeGitBranchName(name: string): string {
  if (!name) return name;
  let n = name.replace(/[[ ~^:?\\*]|\.\./g, "_");
  if (n.endsWith("/") || n.endsWith(".")) {
    n = `${n.slice(0, -1)}_`;
  }
  n = n
    .split("/")
    .map((segment) => (segment.startsWith(".") ? `_${segment.slice(1)}` : segment))
    .join("/");
  n = n.replace(/_+/g, "_");
  return n;
}

export function mergeBranchesMap(
  hgBranchNames: string[],
  defaultBranch: string,
  existing: HgToGitBranchMap = new Map(),
): HgToGitBranchMap {
  const map = new Map(existing);
  const gitDefault = defaultBranch.trim() || "master";
  if (!map.has(HG_DEFAULT_BRANCH)) {
    map.set(HG_DEFAULT_BRANCH, gitDefault);
  }

  for (const hg of hgBranchNames) {
    if (map.has(hg)) continue;
    if (hg === HG_DEFAULT_BRANCH) continue;
    const git = sanitizeGitBranchName(hg);
    map.set(hg, git);
  }

  return map;
}

export function buildHgToGitBranchMap(options: {
  defaultBranch?: string;
  branchesMapPath?: string;
  hgBranchNames?: string[];
}): HgToGitBranchMap {
  const fromFile = options.branchesMapPath
    ? parseBranchesMapFile(options.branchesMapPath)
    : new Map<string, string>();

  if (options.hgBranchNames?.length) {
    return mergeBranchesMap(
      options.hgBranchNames,
      options.defaultBranch ?? "master",
      fromFile,
    );
  }

  const gitDefault = (options.defaultBranch ?? "master").trim() || "master";
  if (!fromFile.has(HG_DEFAULT_BRANCH)) {
    fromFile.set(HG_DEFAULT_BRANCH, gitDefault);
  }
  return fromFile;
}

export function gitBranchForHg(
  hgBranch: string,
  map: HgToGitBranchMap,
): string {
  if (map.has(hgBranch)) return map.get(hgBranch)!;
  return sanitizeGitBranchName(hgBranch);
}

export function hgBranchForGit(
  gitBranch: string,
  map: HgToGitBranchMap,
): string | undefined {
  const lower = gitBranch.toLowerCase();
  for (const [hg, git] of map) {
    if (git === gitBranch || git.toLowerCase() === lower) return hg;
  }
  return undefined;
}

/** Resolve a git branch name case-insensitively (Windows / legacy hg casing). */
export function resolveGitBranchName(
  gitBranches: { name: string }[],
  branchName: string,
): string | undefined {
  const want = branchName.trim();
  if (!want) return undefined;
  const exact = gitBranches.find((b) => b.name === want);
  if (exact) return exact.name;
  const lower = want.toLowerCase();
  return gitBranches.find((b) => b.name.toLowerCase() === lower)?.name;
}

function branchNameScore(
  name: string,
  activeByName: Map<string, { revision?: number }>,
  gitByName: Map<string, unknown>,
  map: HgToGitBranchMap,
): number {
  let score = 0;
  if (activeByName.get(name)?.revision != null) score += 4;
  const mapped = gitBranchForHg(name, map);
  const git = gitByName.get(mapped);
  if (git) score += 8;
  if (gitByName.has(name)) score += 8;
  for (const gitName of gitByName.keys()) {
    if (gitName.toLowerCase() === mapped.toLowerCase() && name === gitName) {
      score += 16;
    }
  }
  return score;
}

/** Prefer the hg label that matches the live git ref casing (e.g. Core over core). */
export function pickCanonicalHgBranchName(
  a: string,
  b: string,
  activeByName: Map<string, { revision?: number }>,
  gitByName: Map<string, unknown>,
  map: HgToGitBranchMap,
): string {
  const scoreA = branchNameScore(a, activeByName, gitByName, map);
  const scoreB = branchNameScore(b, activeByName, gitByName, map);
  if (scoreA !== scoreB) return scoreA > scoreB ? a : b;
  return a.localeCompare(b) <= 0 ? a : b;
}

/** Git branch names accounted for by the hg→git branch map (and active hg heads). */
export function matchedGitBranchNames(
  hgBranches: { name: string }[],
  map: HgToGitBranchMap,
  gitBranches: { name: string }[] = [],
): Set<string> {
  const names = new Set<string>();
  const add = (git: string) => {
    names.add(git);
    const resolved = resolveGitBranchName(gitBranches, git);
    if (resolved) names.add(resolved);
  };
  for (const git of map.values()) add(git);
  for (const b of hgBranches) add(gitBranchForHg(b.name, map));
  return names;
}

/** Union of active hg branch heads and every name in the branches map file. */
export function expandHgBranchesForSnapshot(
  activeBranches: { name: string; revision?: number; tip?: string }[],
  map: HgToGitBranchMap,
  gitBranches: { name: string; tip?: string }[],
): { name: string; revision?: number; tip?: string }[] {
  const activeByName = new Map(activeBranches.map((b) => [b.name, b]));
  const gitByName = new Map(gitBranches.map((b) => [b.name, b]));
  const allNames = new Set<string>([
    ...activeBranches.map((b) => b.name),
    ...map.keys(),
  ]);

  const canonicalByLower = new Map<string, string>();
  for (const name of allNames) {
    const lower = name.toLowerCase();
    const prev = canonicalByLower.get(lower);
    canonicalByLower.set(
      lower,
      prev
        ? pickCanonicalHgBranchName(prev, name, activeByName, gitByName, map)
        : name,
    );
  }

  return [...canonicalByLower.values()]
    .sort((a, b) => a.localeCompare(b))
    .map((name) => {
      const active = activeByName.get(name);
      if (active) return active;
      const mapped = gitBranchForHg(name, map);
      const git =
        gitByName.get(mapped) ??
        gitBranches.find((g) => g.name.toLowerCase() === mapped.toLowerCase());
      return git ? { name, tip: git.tip } : { name };
    });
}
