import {
  parseBranchesMapFile,
  sanitizeGitBranchName,
} from "./branchMapping.js";

/** Mercurial tag name → Git tag name (hg-fast-export -T). */
export type HgToGitTagMap = Map<string, string>;

export const parseTagsMapFile = parseBranchesMapFile;

function quoteMapValue(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function serializeTagsMap(map: HgToGitTagMap): string {
  const lines = [
    "# Generated by hg-to-git (hg-fast-export tag map, UTF-8)",
    '# Format: "hg tag"="git tag"',
    "",
  ];
  const entries = [...map.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  for (const [hg, git] of entries) {
    lines.push(`"${quoteMapValue(hg)}"="${quoteMapValue(git)}"`);
  }
  return `${lines.join("\n")}\n`;
}

/** Matches hg-fast-export `sanitize_name` for tags (same rules as branches). */
export const sanitizeGitTagName = sanitizeGitBranchName;

export function mergeTagsMap(
  hgTagNames: string[],
  existing: HgToGitTagMap = new Map(),
): HgToGitTagMap {
  const map = new Map(existing);
  for (const hg of hgTagNames) {
    if (map.has(hg)) continue;
    if (hg === "tip") continue;
    map.set(hg, sanitizeGitTagName(hg));
  }
  return map;
}
